import { Park } from "./types";

export const parks: Park[] = [
  {
    id: "millenium-park",
    name: "Millennium Park",
    description:
      "The largest public park in Abuja, located in the heart of the city near the Central Business District. A landmark green space offering serene walkways, open lawns, a fountain plaza, and stunning views of Aso Rock.",
    address: "Millennium Park Road, Central Business District, Abuja",
    district: "Central Business District",
    coordinates: { lat: 9.0509, lng: 7.4827 },
    openingHours: {
      weekdays: "6:00 AM – 8:00 PM",
      weekends: "6:00 AM – 9:00 PM",
      publicHolidays: "7:00 AM – 9:00 PM",
    },
    activities: ["Walking", "Jogging", "Cycling", "Picnic", "Playground", "Yoga"],
    rating: 4.6,
    reviewCount: 1842,
    topReviews: [
      {
        author: "Chidi O.",
        rating: 5,
        comment:
          "One of the best parks in Nigeria. Clean, spacious, and very well maintained. Perfect for family outings.",
        date: "2025-11-20",
      },
      {
        author: "Amina B.",
        rating: 5,
        comment:
          "Love the morning jogs here. The atmosphere is peaceful and the paths are well-lit.",
        date: "2025-10-05",
      },
      {
        author: "Tunde A.",
        rating: 4,
        comment: "Great place but can get quite crowded on weekends. Go early for the best experience.",
        date: "2025-09-14",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 5,
    crowdLevel: "High",
    imageUrl: "/images/millennium-park.jpg",
    entryFee: "Free",
    amenities: ["Restrooms", "Parking", "Food Vendors", "Benches", "Fountain"],
    rank: 1,
  },
  {
    id: "life-camp-park",
    name: "Life Camp Recreation Park",
    description:
      "A community-focused outdoor space in the Life Camp district, popular among residents for morning exercise, children's play, and weekend relaxation. Features a multi-use sports court.",
    address: "Life Camp District, Abuja",
    district: "Life Camp",
    coordinates: { lat: 9.1027, lng: 7.4024 },
    openingHours: {
      weekdays: "6:00 AM – 7:00 PM",
      weekends: "6:00 AM – 8:00 PM",
      publicHolidays: "7:00 AM – 7:00 PM",
    },
    activities: ["Walking", "Jogging", "Basketball", "Football", "Playground"],
    rating: 4.1,
    reviewCount: 423,
    topReviews: [
      {
        author: "Ngozi E.",
        rating: 4,
        comment: "Nice and quiet. Good for evening walks with the kids.",
        date: "2025-12-01",
      },
      {
        author: "Emeka P.",
        rating: 4,
        comment: "The basketball court is well maintained. Comes here almost every evening.",
        date: "2025-11-10",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 4,
    crowdLevel: "Moderate",
    imageUrl: "/images/life-camp-park.jpg",
    entryFee: "Free",
    amenities: ["Parking", "Benches", "Sports Court"],
    rank: 2,
  },
  {
    id: "area-1-garden",
    name: "Area 1 Gardens",
    description:
      "A classic neighborhood green space in one of Abuja's oldest residential districts. Well-shaded and quiet, ideal for picnics, reading, and casual strolls.",
    address: "Area 1, Garki, Abuja",
    district: "Garki",
    coordinates: { lat: 9.0337, lng: 7.4873 },
    openingHours: {
      weekdays: "7:00 AM – 6:30 PM",
      weekends: "7:00 AM – 7:00 PM",
      publicHolidays: "8:00 AM – 6:00 PM",
    },
    activities: ["Walking", "Picnic", "Bird Watching", "Yoga"],
    rating: 3.9,
    reviewCount: 218,
    topReviews: [
      {
        author: "Fatima I.",
        rating: 4,
        comment: "Very peaceful. The trees provide great shade during the afternoon heat.",
        date: "2025-10-22",
      },
      {
        author: "Seun A.",
        rating: 3,
        comment: "Needs a bit more maintenance but still a lovely spot for quiet mornings.",
        date: "2025-09-30",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 3,
    crowdLevel: "Low",
    imageUrl: "/images/area1-gardens.jpg",
    entryFee: "Free",
    amenities: ["Benches", "Shade Trees"],
    rank: 3,
  },
  {
    id: "wuse-park",
    name: "Wuse Zone 4 Park",
    description:
      "A vibrant green space at the center of Wuse Zone 4, surrounded by commercial activity. Popular for lunch-break escapes and evening walks.",
    address: "Zone 4, Wuse, Abuja",
    district: "Wuse",
    coordinates: { lat: 9.0583, lng: 7.4921 },
    openingHours: {
      weekdays: "6:30 AM – 8:00 PM",
      weekends: "7:00 AM – 8:30 PM",
      publicHolidays: "7:00 AM – 7:30 PM",
    },
    activities: ["Walking", "Jogging", "Picnic", "Outdoor Gym"],
    rating: 4.0,
    reviewCount: 376,
    topReviews: [
      {
        author: "Kola B.",
        rating: 4,
        comment: "Great outdoor gym equipment. I visit every morning before work.",
        date: "2025-11-18",
      },
      {
        author: "Grace N.",
        rating: 4,
        comment: "Clean and orderly. Good for a quick break from the office.",
        date: "2025-10-07",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 3,
    crowdLevel: "Moderate",
    imageUrl: "/images/wuse-park.jpg",
    entryFee: "Free",
    amenities: ["Outdoor Gym", "Restrooms", "Benches", "Parking"],
    rank: 4,
  },
  {
    id: "gwarinpa-park",
    name: "Gwarinpa Recreational Park",
    description:
      "Serving Nigeria's largest housing estate, this park offers ample open space for sports, community events, and family recreation. Features dedicated cycling and jogging tracks.",
    address: "1st Avenue, Gwarinpa Estate, Abuja",
    district: "Gwarinpa",
    coordinates: { lat: 9.1195, lng: 7.4147 },
    openingHours: {
      weekdays: "5:30 AM – 8:00 PM",
      weekends: "5:30 AM – 9:00 PM",
      publicHolidays: "6:00 AM – 8:00 PM",
    },
    activities: ["Walking", "Jogging", "Cycling", "Football", "Tennis", "Playground", "Picnic"],
    rating: 4.3,
    reviewCount: 694,
    topReviews: [
      {
        author: "David M.",
        rating: 5,
        comment: "The cycling track is fantastic. Clean environment, friendly crowd.",
        date: "2025-12-03",
      },
      {
        author: "Ada C.",
        rating: 4,
        comment: "Love bringing the family here on Saturdays. The kids enjoy the playground.",
        date: "2025-11-28",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 5,
    crowdLevel: "High",
    imageUrl: "/images/gwarinpa-park.jpg",
    entryFee: "Free",
    amenities: ["Restrooms", "Parking", "Cycling Track", "Tennis Court", "Playground", "Food Vendors"],
    rank: 5,
  },
  {
    id: "maitama-gardens",
    name: "Maitama Botanical Gardens",
    description:
      "A carefully curated botanical garden in the upscale Maitama district. Home to a wide variety of native Nigerian flora, bird watching trails, and shaded picnic areas.",
    address: "Bangui Street, Maitama, Abuja",
    district: "Maitama",
    coordinates: { lat: 9.0836, lng: 7.4941 },
    openingHours: {
      weekdays: "8:00 AM – 5:30 PM",
      weekends: "8:00 AM – 6:00 PM",
      publicHolidays: "9:00 AM – 5:00 PM",
    },
    activities: ["Walking", "Bird Watching", "Nature Trails", "Picnic", "Yoga"],
    rating: 4.4,
    reviewCount: 531,
    topReviews: [
      {
        author: "Yemi A.",
        rating: 5,
        comment: "Absolutely beautiful. The variety of plants is impressive and the staff are helpful.",
        date: "2025-11-05",
      },
      {
        author: "Bisi L.",
        rating: 4,
        comment: "Perfect spot for weekend relaxation. Saw three different bird species!",
        date: "2025-10-19",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 4,
    crowdLevel: "Low",
    imageUrl: "/images/maitama-gardens.jpg",
    entryFee: "₦500 per person",
    amenities: ["Restrooms", "Parking", "Guide Service", "Benches", "Water Fountain"],
    rank: 6,
  },
  {
    id: "jabi-lake-garden",
    name: "Jabi Lake Garden",
    description:
      "A lakeside recreation space near Jabi Lake Mall with open lawns, jogging loops, and family picnic zones that stay lively through evenings.",
    address: "Bala Sokoto Way, Jabi, Abuja",
    district: "Jabi",
    coordinates: { lat: 9.0745, lng: 7.4264 },
    openingHours: {
      weekdays: "6:00 AM – 8:30 PM",
      weekends: "6:00 AM – 9:00 PM",
      publicHolidays: "7:00 AM – 9:00 PM",
    },
    activities: ["Walking", "Jogging", "Picnic", "Fishing", "Playground"],
    rating: 4.5,
    reviewCount: 911,
    topReviews: [
      {
        author: "Ruth I.",
        rating: 5,
        comment: "Great sunset views and very clean walkways around the lake.",
        date: "2025-12-08",
      },
      {
        author: "Adewale T.",
        rating: 4,
        comment: "Perfect for weekend picnics. Parking fills up quickly though.",
        date: "2025-11-29",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 5,
    crowdLevel: "High",
    imageUrl: "/images/millennium-park.jpg",
    entryFee: "₦1,000 per adult",
    amenities: ["Restrooms", "Parking", "Food Vendors", "Boat Jetty", "Playground"],
    rank: 7,
  },
  {
    id: "asokoro-green-park",
    name: "Asokoro Green Park",
    description:
      "A calm neighborhood park with mature trees and shaded paths, ideal for light workouts and short evening relaxation.",
    address: "Yedseram Street, Asokoro, Abuja",
    district: "Asokoro",
    coordinates: { lat: 9.0494, lng: 7.517 },
    openingHours: {
      weekdays: "6:30 AM – 7:30 PM",
      weekends: "6:30 AM – 8:00 PM",
      publicHolidays: "7:00 AM – 7:30 PM",
    },
    activities: ["Walking", "Yoga", "Picnic", "Bird Watching"],
    rating: 4.2,
    reviewCount: 289,
    topReviews: [
      {
        author: "Maryam S.",
        rating: 4,
        comment: "Quiet and safe. A lovely place for breathing space after work.",
        date: "2025-12-04",
      },
      {
        author: "Uche K.",
        rating: 4,
        comment: "Well-kept lawns and lots of shade for reading.",
        date: "2025-10-18",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 4,
    crowdLevel: "Low",
    imageUrl: "/images/maitama-gardens.jpg",
    entryFee: "Free",
    amenities: ["Benches", "Restrooms", "Parking", "Shade Trees"],
    rank: 8,
  },
  {
    id: "utako-family-park",
    name: "Utako Family Park",
    description:
      "A compact but active community recreation hub known for children's play areas and fitness classes on weekend mornings.",
    address: "Sani Abacha Way, Utako, Abuja",
    district: "Utako",
    coordinates: { lat: 9.0789, lng: 7.4452 },
    openingHours: {
      weekdays: "6:00 AM – 8:00 PM",
      weekends: "6:00 AM – 8:30 PM",
      publicHolidays: "7:00 AM – 8:00 PM",
    },
    activities: ["Walking", "Outdoor Gym", "Playground", "Basketball"],
    rating: 4.0,
    reviewCount: 334,
    topReviews: [
      {
        author: "Damilola F.",
        rating: 4,
        comment: "The kids' zone is secure and the staff are polite.",
        date: "2025-11-17",
      },
      {
        author: "Femi O.",
        rating: 4,
        comment: "Good community vibe and decent outdoor workout setup.",
        date: "2025-10-30",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 5,
    crowdLevel: "Moderate",
    imageUrl: "/images/life-camp-park.jpg",
    entryFee: "₦500 per adult",
    amenities: ["Playground", "Outdoor Gym", "Parking", "Snack Stand"],
    rank: 9,
  },
  {
    id: "kubwa-recreation-ground",
    name: "Kubwa Recreation Ground",
    description:
      "An expansive local field and green belt in Kubwa for team sports, cycling, and casual evening gatherings.",
    address: "Arab Road, Kubwa, Abuja",
    district: "Kubwa",
    coordinates: { lat: 9.1658, lng: 7.3258 },
    openingHours: {
      weekdays: "5:30 AM – 8:00 PM",
      weekends: "5:30 AM – 8:30 PM",
      publicHolidays: "6:00 AM – 8:00 PM",
    },
    activities: ["Walking", "Jogging", "Cycling", "Football", "Picnic"],
    rating: 3.8,
    reviewCount: 257,
    topReviews: [
      {
        author: "Bello H.",
        rating: 4,
        comment: "Great open space for football and evening runs.",
        date: "2025-11-12",
      },
      {
        author: "Monica A.",
        rating: 3,
        comment: "Very spacious. Would be better with more lighting.",
        date: "2025-09-25",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 3,
    crowdLevel: "Moderate",
    imageUrl: "/images/gwarinpa-park.jpg",
    entryFee: "Free",
    amenities: ["Parking", "Football Pitch", "Cycling Track", "Benches"],
    rank: 10,
  },
  {
    id: "apo-urban-garden",
    name: "Apo Urban Garden",
    description:
      "A modern urban green escape with landscaped paths, small event lawns, and birdlife-friendly planting around Apo axis.",
    address: "Apo Resettlement, Abuja",
    district: "Apo",
    coordinates: { lat: 9.0133, lng: 7.5179 },
    openingHours: {
      weekdays: "7:00 AM – 7:00 PM",
      weekends: "7:00 AM – 8:00 PM",
      publicHolidays: "8:00 AM – 7:00 PM",
    },
    activities: ["Walking", "Nature Trails", "Yoga", "Bird Watching", "Picnic"],
    rating: 4.1,
    reviewCount: 201,
    topReviews: [
      {
        author: "Nkechi J.",
        rating: 4,
        comment: "Beautiful landscaping and calm atmosphere all day.",
        date: "2025-12-02",
      },
      {
        author: "Paul E.",
        rating: 4,
        comment: "Good for yoga sessions and small group meetups.",
        date: "2025-11-09",
      },
    ],
    familyFriendly: true,
    familyFriendlinessScore: 4,
    crowdLevel: "Low",
    imageUrl: "/images/area1-gardens.jpg",
    entryFee: "₦300 per person",
    amenities: ["Benches", "Restrooms", "Parking", "Event Lawn"],
    rank: 11,
  },
];

export const allActivities = [
  "Walking",
  "Jogging",
  "Cycling",
  "Picnic",
  "Swimming",
  "Tennis",
  "Football",
  "Basketball",
  "Nature Trails",
  "Bird Watching",
  "Playground",
  "Fishing",
  "Yoga",
  "Outdoor Gym",
] as const;

export const allDistricts = [
  "Central Business District",
  "Life Camp",
  "Garki",
  "Wuse",
  "Gwarinpa",
  "Maitama",
  "Jabi",
  "Asokoro",
  "Utako",
  "Kubwa",
  "Apo",
];
